#!/usr/bin/env python3
"""
cowdiff — GNO ProDOS disk image extraction and comparison tool.

Modes
-----
  cowdiff <reference> <source>           compare two images/directories
  cowdiff compare <reference> <source>   same, explicit subcommand
  cowdiff extract <image>                extract image to cache; print cache path
  cowdiff cache --list                   list cached extractions
  cowdiff cache --clear                  delete all cached extractions

Inputs (reference / source / image)
------------------------------------
  *.po / *.2mg / *.hdv / *.dsk   ProDOS disk image  → extracted to cache automatically
  directory with metadata.json   pre-extracted tree  → metadata reused
  directory without metadata.json                    → metadata generated in-place
  metadata.json file directly                        → loaded directly

Cache
-----
  Default root : ~/.cache/cowdiff/
  Key          : SHA-256 of the disk image file
  Invalidation : automatic when image file changes (hash no longer matches)
  Override     : --cache-dir DIR   or   --out DIR (extract mode, bypasses cache)
"""

import argparse
import hashlib
import json
import os
import re
import shutil
import struct
import subprocess
import sys
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# ── Version / constants ────────────────────────────────────────────────────────

VERSION = '1.0.0'
CACHE_ROOT = Path.home() / '.cache' / 'cowdiff'

DEFAULT_CADIUS_PATHS = [
    Path.home() / 'source' / 'cadius' / 'cadius',
    Path('/usr/local/bin/cadius'),
    Path('/opt/homebrew/bin/cadius'),
]

DISK_EXTS = {'.po', '.2mg', '.hdv', '.dsk', '.img'}
CADIUS_RE = re.compile(r'^(.+)#([0-9A-Fa-f]{2})([0-9A-Fa-f]{4})$')
RSRC_SUFFIX = '_ResourceFork.bin'

# ProDOS type code → short name
TYPE_NAMES: Dict[int, str] = {
    0x00: 'TYP', 0x04: 'TXT', 0x06: 'BIN', 0x0D: 'TXT', 0x0F: 'DIR',
    0xB0: 'OBJ', 0xB1: 'OBJ', 0xB2: 'LIB', 0xB3: 'S16', 0xB4: 'RTL',
    0xB5: 'EXE', 0xBB: 'DVR', 0xC9: 'FDT', 0xCA: 'FON',
}

# Types that must be built from source (not text/config)
BUILD_TYPES = {'B5', 'B3', 'BB', 'B2', 'B1', 'B0'}

# Paths that come from the GoldenGate SDK, not gno-obj/
EXEMPT_PATHS = {'/lib/orcalib', '/lib/sysfloat'}

# Files generated by cowdiff itself — skip when scanning
COWDIFF_FILES = {'metadata.json', 'generate_metadata.py', 'cowdiff.py'}

# ── ANSI colour helpers ────────────────────────────────────────────────────────

def _c(code: str) -> str:
    return f'\033[{code}m' if sys.stdout.isatty() else ''

RED    = _c('31')
GREEN  = _c('32')
YELLOW = _c('33')
CYAN   = _c('36')
BOLD   = _c('1')
DIM    = _c('2')
NC     = _c('0')

# ── FileEntry ─────────────────────────────────────────────────────────────────

@dataclass
class FileEntry:
    prodos_path:      str
    type_hex:         str
    auxtype_hex:      str
    type_name:        str
    data_size:        int
    has_resource_fork: bool
    rsrc_size:        int
    sha256:           str
    md5:              str
    rsrc_sha256:      Optional[str] = None
    rsrc_md5:         Optional[str] = None
    rsrc_extracted_path: Optional[str] = None
    extracted_path:   str = ''

    @property
    def key(self) -> str:
        return self.prodos_path.lower()

    @property
    def basename_lower(self) -> str:
        return self.prodos_path.rsplit('/', 1)[-1].lower()

    @property
    def is_binary(self) -> bool:
        return self.type_hex.upper() in BUILD_TYPES

    @property
    def is_exempt(self) -> bool:
        return self.prodos_path.lower() in EXEMPT_PATHS


Manifest = Dict[str, FileEntry]   # keyed by prodos_path.lower()

# ── Hashing ───────────────────────────────────────────────────────────────────

def _hash_path(path: Path, algo: str = 'sha256') -> str:
    h = hashlib.new(algo)
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(65536), b''):
            h.update(chunk)
    return h.hexdigest()


def hash_image(path: Path, quiet: bool = False) -> str:
    size_mb = path.stat().st_size / 1_048_576
    if not quiet:
        print(f'  Hashing {path.name} ({size_mb:.1f} MB)...', end=' ', flush=True)
    digest = _hash_path(path)
    if not quiet:
        print(f'sha256={digest[:16]}...')
    return digest

# ── cadius integration ────────────────────────────────────────────────────────

def find_cadius(hint: Optional[str] = None) -> Path:
    candidates = [Path(hint)] if hint else []
    candidates.extend(DEFAULT_CADIUS_PATHS)
    for c in candidates:
        if c.exists() and os.access(c, os.X_OK):
            return c
    raise FileNotFoundError(
        'cadius not found. Build from https://github.com/mach-kernel/cadius.git\n'
        '  git clone https://github.com/mach-kernel/cadius.git ~/source/cadius\n'
        '  cd ~/source/cadius && make\n'
        'or pass --cadius /path/to/cadius'
    )


def run_cadius_extract(cadius: Path, image: Path, out_dir: Path,
                       verbose: bool = False) -> Tuple[int, int]:
    """Run cadius EXTRACTVOLUME; return (files, folders) count."""
    out_dir.mkdir(parents=True, exist_ok=True)
    cmd = [str(cadius), 'EXTRACTVOLUME', str(image), str(out_dir) + '/']
    if verbose:
        print(f'  $ {" ".join(cmd)}')
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f'cadius failed (exit {result.returncode}):\n{result.stderr.strip()}')
    m_files   = re.search(r'File\(s\)\s*:\s*(\d+)',   result.stdout)
    m_folders = re.search(r'Folder\(s\)\s*:\s*(\d+)', result.stdout)
    m_errors  = re.search(r'Error\(s\)\s*:\s*(\d+)',  result.stdout)
    files   = int(m_files.group(1))   if m_files   else 0
    folders = int(m_folders.group(1)) if m_folders else 0
    errors  = int(m_errors.group(1))  if m_errors  else 0
    if errors:
        print(f'  {YELLOW}WARNING: cadius reported {errors} error(s){NC}', file=sys.stderr)
    return files, folders

# ── Metadata generation ───────────────────────────────────────────────────────

def _parse_cadius_name(name: str) -> Optional[Tuple[str, str, str]]:
    """Return (basename, type_hex_upper, auxtype_hex_upper) or None."""
    m = CADIUS_RE.match(name)
    if m:
        return m.group(1), m.group(2).upper(), m.group(3).upper()
    return None


def _make_prodos_path(rel: Path) -> str:
    """
    Convert a path relative to the extraction root into a canonical ProDOS path.
    Strips the volume-label directory (first component) and #TTAAAA suffix.
    """
    parts = list(rel.parts)
    if not parts:
        return '/'
    parts = parts[1:]          # drop volume label (e.g. 'GNO')
    if not parts:
        return '/'
    last = parts[-1]
    parsed = _parse_cadius_name(last)
    if parsed:
        last = parsed[0]       # strip #TTAAAA
    return '/' + '/'.join(parts[:-1] + [last])


def _entry_from_file(path: Path, rel: Path, rsrc_set: set,
                     root: Path) -> Optional[FileEntry]:
    """Build a FileEntry from a cadius-extracted data file."""
    parsed = _parse_cadius_name(path.name)
    if not parsed:
        return None            # _FileInformation.txt etc.
    basename, type_hex, auxtype_hex = parsed
    type_int  = int(type_hex, 16)
    type_name = TYPE_NAMES.get(type_int, f'${type_hex}')
    data_size = path.stat().st_size

    rsrc_path = path.parent / (path.name + RSRC_SUFFIX)
    has_rsrc  = rsrc_path in rsrc_set
    rsrc_size = rsrc_path.stat().st_size if has_rsrc else 0

    prodos = _make_prodos_path(rel)

    entry = FileEntry(
        prodos_path      = prodos,
        type_hex         = type_hex,
        auxtype_hex      = auxtype_hex,
        type_name        = type_name,
        data_size        = data_size,
        has_resource_fork= has_rsrc,
        rsrc_size        = rsrc_size,
        sha256           = _hash_path(path),
        md5              = _hash_path(path, 'md5'),
        extracted_path   = str(rel),
    )
    if has_rsrc:
        entry.rsrc_sha256          = _hash_path(rsrc_path)
        entry.rsrc_md5             = _hash_path(rsrc_path, 'md5')
        entry.rsrc_extracted_path  = str(rsrc_path.relative_to(root))
    return entry


def generate_metadata(
    extracted_dir:  Path,
    image_path:     Optional[Path] = None,
    image_sha256:   Optional[str]  = None,
    verbose:        bool = False,
) -> dict:
    """
    Walk a cadius-extracted tree, build metadata, write metadata.json, and
    return the metadata dict.
    """
    # Find the volume root subdir (what cadius created)
    vol_candidates = [p for p in extracted_dir.iterdir()
                      if p.is_dir() and p.name not in {'__MACOSX'}]
    if not vol_candidates:
        raise RuntimeError(f'No volume subdirectory found in {extracted_dir}')
    vol_root  = vol_candidates[0]
    vol_label = vol_root.name

    # Collect resource-fork sidecar paths for O(1) lookup
    rsrc_set: set = set()
    for p in vol_root.rglob('*'):
        if p.name.endswith(RSRC_SUFFIX):
            rsrc_set.add(p)

    files_meta: List[FileEntry] = []
    dirs_meta:  List[str]       = []

    for path in sorted(vol_root.rglob('*')):
        if path in rsrc_set:
            continue
        if path.name in COWDIFF_FILES:
            continue
        rel = path.relative_to(extracted_dir)
        if path.is_dir():
            dirs_meta.append(_make_prodos_path(rel))
            continue
        entry = _entry_from_file(path, rel, rsrc_set, extracted_dir)
        if entry is None:
            continue
        if verbose:
            rsrc_tag = f' +rsrc {entry.rsrc_size}B' if entry.has_resource_fork else ''
            print(f'  {entry.prodos_path:<50} [{entry.type_name}/${entry.type_hex}] '
                  f'{entry.data_size}B{rsrc_tag}')
        files_meta.append(entry)

    files_meta.sort(key=lambda e: e.prodos_path.upper())
    dirs_meta.sort(key=str.upper)

    meta = {
        'cowdiff_version': VERSION,
        'generated':       datetime.now(timezone.utc).isoformat(),
        'volume_label':    vol_label,
        'extracted_dir':   str(extracted_dir),
        'source_image':    str(image_path) if image_path else None,
        'source_sha256':   image_sha256,
        'tool':            'cadius EXTRACTVOLUME',
        'stats':           {'files': len(files_meta), 'folders': len(dirs_meta)},
        'files':           [asdict(e) for e in files_meta],
        'folders':         [{'prodos_path': d} for d in dirs_meta],
    }
    out_path = extracted_dir / 'metadata.json'
    with open(out_path, 'w') as f:
        json.dump(meta, f, indent=2)
    return meta

# ── Cache helpers ─────────────────────────────────────────────────────────────

def _cache_dir(sha256: str, root: Path = CACHE_ROOT) -> Path:
    return root / sha256


def _cache_valid(cache_dir: Path, expected_sha256: str) -> bool:
    meta_path = cache_dir / 'metadata.json'
    if not meta_path.exists():
        return False
    try:
        with open(meta_path) as f:
            m = json.load(f)
        return m.get('source_sha256') == expected_sha256
    except Exception:
        return False

# ── Manifest loading ──────────────────────────────────────────────────────────

def _manifest_from_meta(meta: dict) -> Manifest:
    known = set(FileEntry.__dataclass_fields__)
    manifest: Manifest = {}
    for d in meta.get('files', []):
        filtered = {k: v for k, v in d.items() if k in known}
        try:
            e = FileEntry(**filtered)
            manifest[e.key] = e
        except TypeError:
            pass   # skip malformed entries
    return manifest

# ── Source information ────────────────────────────────────────────────────────

@dataclass
class SourceInfo:
    label:          str
    original_path:  Path
    cache_dir:      Optional[Path] = None
    extracted_dir:  Optional[Path] = None
    stats:          dict = field(default_factory=dict)

# ── Input resolution ──────────────────────────────────────────────────────────

def resolve_input(
    path_str:   str,
    cadius:     Path,
    cache_root: Path    = CACHE_ROOT,
    no_cache:   bool    = False,
    out_dir:    Optional[Path] = None,
    quiet:      bool    = False,
) -> Tuple[Manifest, SourceInfo]:
    path = Path(path_str).expanduser().resolve()

    # ── metadata.json file ──────────────────────────────────────────────────
    if path.is_file() and path.name == 'metadata.json':
        with open(path) as f:
            meta = json.load(f)
        info = SourceInfo(
            label         = str(path),
            original_path = path,
            extracted_dir = path.parent,
            stats         = meta.get('stats', {}),
        )
        return _manifest_from_meta(meta), info

    # ── disk image file ─────────────────────────────────────────────────────
    if path.is_file() and path.suffix.lower() in DISK_EXTS:
        sha = hash_image(path, quiet=quiet)

        extract_to = out_dir if out_dir else _cache_dir(sha, cache_root)

        if not no_cache and _cache_valid(extract_to, sha):
            if not quiet:
                print(f'  Cache hit → {extract_to}')
        else:
            if extract_to.exists():
                shutil.rmtree(extract_to)
            if not quiet:
                print(f'  Extracting {path.name} with cadius...', end=' ', flush=True)
            files, folders = run_cadius_extract(cadius, path, extract_to,
                                                verbose=False)
            if not quiet:
                print(f'{files} files, {folders} folders')
                print(f'  Generating metadata...', end=' ', flush=True)
            meta = generate_metadata(extract_to, image_path=path,
                                     image_sha256=sha, verbose=False)
            if not quiet:
                print(f'{meta["stats"]["files"]} entries')

        with open(extract_to / 'metadata.json') as f:
            meta = json.load(f)

        info = SourceInfo(
            label         = path.name,
            original_path = path,
            cache_dir     = None if out_dir else extract_to,
            extracted_dir = extract_to,
            stats         = meta.get('stats', {}),
        )
        return _manifest_from_meta(meta), info

    # ── extracted directory ─────────────────────────────────────────────────
    if path.is_dir():
        meta_path = path / 'metadata.json'
        if meta_path.exists() and not no_cache:
            if not quiet:
                print(f'  Using existing metadata.json in {path.name}/')
            with open(meta_path) as f:
                meta = json.load(f)
        else:
            if not quiet:
                print(f'  Generating metadata for {path.name}/...', end=' ', flush=True)
            meta = generate_metadata(path, verbose=False)
            if not quiet:
                print(f'{meta["stats"]["files"]} entries')
        info = SourceInfo(
            label         = path.name,
            original_path = path,
            extracted_dir = path,
            stats         = meta.get('stats', {}),
        )
        return _manifest_from_meta(meta), info

    raise ValueError(
        f'Cannot interpret input: {path_str}\n'
        '  Expected a .po/.2mg/.hdv disk image, an extracted directory, '
        'or a metadata.json file.'
    )

# ── Comparison data model ─────────────────────────────────────────────────────

@dataclass
class PathMismatch:
    """File present in source at a different path, with identical name+content."""
    ref_entry: FileEntry
    src_entry: FileEntry

    @property
    def note(self) -> str:
        return (f'content identical, size={_fmt_size(self.ref_entry.data_size)}'
                if self.ref_entry.sha256 == self.src_entry.sha256
                else f'content differs ref={_fmt_size(self.ref_entry.data_size)} '
                     f'src={_fmt_size(self.src_entry.data_size)}')


@dataclass
class CompareResult:
    identical:       List[Tuple[FileEntry, FileEntry]]        = field(default_factory=list)
    content_differs: List[Tuple[FileEntry, FileEntry]]        = field(default_factory=list)
    type_differs:    List[Tuple[FileEntry, FileEntry]]        = field(default_factory=list)
    rsrc_changed:    List[Tuple[FileEntry, FileEntry, str]]   = field(default_factory=list)
    path_mismatch:   List[PathMismatch]                       = field(default_factory=list)
    missing:         List[FileEntry]                          = field(default_factory=list)
    extra:           List[FileEntry]                          = field(default_factory=list)
    exempt:          List[FileEntry]                          = field(default_factory=list)

# ── Comparison engine ─────────────────────────────────────────────────────────

def _build_reverse_index(manifest: Manifest) -> Dict[Tuple[str, str], List[FileEntry]]:
    """Index entries by (basename_lower, sha256) for precise path-mismatch detection."""
    idx: Dict[Tuple[str, str], List[FileEntry]] = {}
    for e in manifest.values():
        key = (e.basename_lower, e.sha256)
        idx.setdefault(key, []).append(e)
    return idx


def compare_manifests(ref: Manifest, src: Manifest) -> CompareResult:
    result = CompareResult()
    src_reverse = _build_reverse_index(src)
    claimed_src_keys: set = set()   # src keys that have been matched to a ref entry

    for ref_key, ref_e in ref.items():

        # ── exempt ──────────────────────────────────────────────────────────
        if ref_e.is_exempt:
            result.exempt.append(ref_e)
            continue

        if ref_key in src:
            # ── same path ────────────────────────────────────────────────────
            src_e = src[ref_key]
            claimed_src_keys.add(ref_key)

            if ref_e.type_hex != src_e.type_hex or ref_e.auxtype_hex != src_e.auxtype_hex:
                result.type_differs.append((ref_e, src_e))
                continue

            data_match = ref_e.sha256 == src_e.sha256
            rsrc_presence_match = ref_e.has_resource_fork == src_e.has_resource_fork
            rsrc_content_match  = (ref_e.rsrc_sha256 or '') == (src_e.rsrc_sha256 or '')

            if data_match and rsrc_presence_match and rsrc_content_match:
                result.identical.append((ref_e, src_e))
            elif not data_match:
                result.content_differs.append((ref_e, src_e))
            else:
                # data matches, resource fork differs
                if not rsrc_presence_match:
                    note = 'added' if src_e.has_resource_fork else 'removed'
                else:
                    note = 'changed'
                result.rsrc_changed.append((ref_e, src_e, note))

        else:
            # ── not at expected path ─────────────────────────────────────────
            # Look for (same basename, same SHA-256) anywhere in source
            pm_key = (ref_e.basename_lower, ref_e.sha256)
            if pm_key in src_reverse:
                src_e = src_reverse[pm_key][0]   # first match (most cases: unique)
                claimed_src_keys.add(src_e.key)
                result.path_mismatch.append(PathMismatch(ref_e, src_e))
            else:
                result.missing.append(ref_e)

    # ── extra: in source but not in reference (and not already claimed) ──────
    for src_key, src_e in src.items():
        if src_key not in ref and src_key not in claimed_src_keys:
            result.extra.append(src_e)

    # Stable sort for all categories
    _k  = lambda x: x[0].prodos_path.upper()    # for tuples
    _ke = lambda x: x.prodos_path.upper()        # for single entries
    _kp = lambda x: x.ref_entry.prodos_path.upper()

    result.identical.sort(key=_k)
    result.content_differs.sort(key=_k)
    result.type_differs.sort(key=_k)
    result.rsrc_changed.sort(key=_k)
    result.path_mismatch.sort(key=_kp)
    result.missing.sort(key=_ke)
    result.extra.sort(key=_ke)
    result.exempt.sort(key=_ke)

    return result

# ── OMF segment diff ──────────────────────────────────────────────────────────

OMF_SEG_TYPES = {
    0x00: 'CODE', 0x01: 'DATA', 0x02: 'JUMP', 0x04: 'PATH',
    0x08: 'LDICT', 0x10: 'INIT', 0x11: 'ABS', 0x1F: 'DP',
}


def _parse_omf_segments(data: bytes) -> List[dict]:
    """
    Parse OMF v2 segment headers (name, type, byte_count only — no body decode).
    Returns list of dicts: {name, type_name, byte_count}.
    Stops on malformed/non-OMF data; returns whatever was parsed so far.
    """
    segs = []
    offset = 0
    seg_num = 0
    while offset + 0x2C <= len(data):
        sd = data[offset:]
        version = sd[0x0F]
        if version not in (0, 1, 2):
            break
        byte_count = struct.unpack_from('<I', sd, 0x00)[0]
        if byte_count == 0 or offset + byte_count > len(data):
            break
        lab_len  = sd[0x0D]
        kind     = struct.unpack_from('<H', sd, 0x14)[0] if version == 2 else (sd[0x0A] & 0x1F)
        seg_type = kind & 0x1F
        dispname = struct.unpack_from('<H', sd, 0x28)[0]
        dispdata = struct.unpack_from('<H', sd, 0x2A)[0]
        chunk    = data[offset: offset + byte_count]
        try:
            if lab_len == 0:
                # Pascal string, right-aligned with leading 0x20 padding
                p = dispname
                while p < dispdata and chunk[p] == 0x20:
                    p += 1
                if p < dispdata:
                    nlen = chunk[p]
                    name = chunk[p + 1: p + 1 + nlen].decode('ascii', errors='replace')
                else:
                    name = f'<{seg_num + 1}>'
            else:
                name = chunk[dispname: dispname + lab_len].rstrip(b'\x00 ').decode('ascii', errors='replace')
        except Exception:
            name = f'<{seg_num + 1}>'
        segs.append({
            'name':       name,
            'type_name':  OMF_SEG_TYPES.get(seg_type, f'${seg_type:02X}'),
            'byte_count': byte_count,
        })
        seg_num += 1
        offset  += byte_count
    return segs


def _omf_diff_lines(ref_segs: List[dict], src_segs: List[dict],
                    prefix: str = '    ') -> List[str]:
    """
    Compare two OMF segment lists. Returns formatted display lines.
    Segments are matched by name (case-sensitive, ORCA/C names are uppercase).
    Within a name, matched by position. Identical-size matches are summarised,
    not listed individually.
    """
    lines: List[str] = []
    rc, sc = len(ref_segs), len(src_segs)

    # Header: segment counts
    count_tag = f'  {YELLOW}← count differs{NC}' if rc != sc else ''
    lines.append(
        f'{prefix}OMF: ref={rc} seg{"s" if rc != 1 else ""}  '
        f'src={sc} seg{"s" if sc != 1 else ""}{count_tag}'
    )

    # Group by name preserving encounter order
    ref_by_name: Dict[str, list] = {}
    for s in ref_segs:
        ref_by_name.setdefault(s['name'], []).append(s)
    src_by_name: Dict[str, list] = {}
    for s in src_segs:
        src_by_name.setdefault(s['name'], []).append(s)

    # Ordered union of names
    seen: set = set()
    all_names: List[str] = []
    for s in ref_segs + src_segs:
        if s['name'] not in seen:
            all_names.append(s['name'])
            seen.add(s['name'])

    n_identical = 0
    detail_lines: List[str] = []

    for name in all_names:
        r_list = ref_by_name.get(name, [])
        s_list = src_by_name.get(name, [])
        max_len = max(len(r_list), len(s_list))
        for i in range(max_len):
            rs = r_list[i] if i < len(r_list) else None
            ss = s_list[i] if i < len(s_list) else None
            label = name if max_len == 1 else f'{name}[{i}]'
            if rs and ss:
                delta = ss['byte_count'] - rs['byte_count']
                if delta == 0:
                    n_identical += 1
                    continue
                col = YELLOW if abs(delta) < 1024 else RED
                detail_lines.append(
                    f'{prefix}  {label or "<unnamed>":<28} {rs["type_name"]:<5}  '
                    f'ref={rs["byte_count"]:>8,}B  src={ss["byte_count"]:>8,}B  '
                    f'{col}{delta:+,}B{NC}'
                )
            elif rs:
                detail_lines.append(
                    f'{prefix}  {RED}MISSING  {label or "<unnamed>":<24} {rs["type_name"]:<5}  '
                    f'ref={rs["byte_count"]:>8,}B{NC}'
                )
            else:
                detail_lines.append(
                    f'{prefix}  {CYAN}EXTRA    {label or "<unnamed>":<24} {ss["type_name"]:<5}  '
                    f'src={ss["byte_count"]:>8,}B{NC}'
                )

    if n_identical:
        lines.append(
            f'{prefix}  {DIM}{n_identical} segment{"s" if n_identical != 1 else ""} '
            f'with identical name+size (not shown){NC}'
        )
    lines.extend(detail_lines)
    return lines


def _omf_diff_for_entry(
    ref_e: 'FileEntry', src_e: 'FileEntry',
    ref_info: 'SourceInfo', src_info: 'SourceInfo',
) -> Optional[List[str]]:
    """
    Resolve both FileEntry extracted paths, read the binaries, parse OMF,
    and return formatted diff lines. Returns None on any error or if files
    are not OMF (e.g. no segments parsed from either side).
    """
    if not ref_e.extracted_path or not src_e.extracted_path:
        return None
    if not ref_info.extracted_dir or not src_info.extracted_dir:
        return None
    ref_path = ref_info.extracted_dir / ref_e.extracted_path
    src_path = src_info.extracted_dir / src_e.extracted_path
    try:
        ref_data = ref_path.read_bytes()
        src_data = src_path.read_bytes()
    except (FileNotFoundError, PermissionError, OSError):
        return None
    try:
        ref_segs = _parse_omf_segments(ref_data)
        src_segs = _parse_omf_segments(src_data)
    except Exception:
        return None
    if not ref_segs and not src_segs:
        return None   # not OMF
    return _omf_diff_lines(ref_segs, src_segs)


# ── Formatting helpers ────────────────────────────────────────────────────────

def _fmt_size(n: int) -> str:
    if n >= 1_048_576: return f'{n/1_048_576:.1f}MB'
    if n >= 1_024:     return f'{n/1_024:.1f}KB'
    return f'{n}B'


def _fmt_delta(n: int) -> str:
    sign = '+' if n >= 0 else ''
    return f'{sign}{_fmt_size(n)}'


def _divider(title: str = '', width: int = 72) -> str:
    if title:
        return f'{"─" * 2} {title} {"─" * max(0, width - len(title) - 4)}'
    return '─' * width

# ── Human-readable report ─────────────────────────────────────────────────────

def print_report(result: CompareResult, ref_info: SourceInfo, src_info: SourceInfo,
                 opts: argparse.Namespace) -> None:

    show_all  = not any([opts.missing, opts.extra, opts.different, opts.identical])
    show_mis  = show_all or opts.missing
    show_ext  = show_all or opts.extra
    show_dif  = show_all or opts.different
    show_ide  = show_all or opts.identical
    verbose   = getattr(opts, 'verbose', False)
    W = 52    # path column width

    def section(title: str, color: str = BOLD) -> None:
        print(f'\n{color}{_divider(title)}{NC}')

    # ── header ───────────────────────────────────────────────────────────────
    print(f'\n{BOLD}cowdiff {VERSION} — GNO Disk Image Comparison{NC}')
    print('=' * 72)
    for label, info in (('Reference', ref_info), ('Source   ', src_info)):
        print(f'  {label} : {info.label}')
        if info.cache_dir:
            print(f'  {"":11}  {DIM}[cache: {info.cache_dir}]{NC}')
        elif info.extracted_dir:
            print(f'  {"":11}  {DIM}[dir: {info.extracted_dir}]{NC}')
    print(f'  Generated  : {datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%MZ")}')

    # ── summary ───────────────────────────────────────────────────────────────
    total_ref = (len(result.identical) + len(result.content_differs) +
                 len(result.type_differs) + len(result.rsrc_changed) +
                 len(result.path_mismatch) + len(result.missing) + len(result.exempt))
    binary_counts = {
        'ref_built': sum(1 for r, s in result.identical       if r.is_binary) +
                     sum(1 for r, s in result.content_differs  if r.is_binary) +
                     sum(1 for r, s in result.type_differs     if r.is_binary) +
                     sum(1 for r, s, _ in result.rsrc_changed  if r.is_binary) +
                     sum(1 for pm    in result.path_mismatch   if pm.ref_entry.is_binary),
    }

    section('SUMMARY')
    print(f'  {"Reference entries":<28}: {total_ref:4d}  '
          f'({binary_counts["ref_built"] + len(result.missing)} build-required binaries)')
    print(f'  {"Identical":<28}: {GREEN}{len(result.identical):4d}{NC}')
    print(f'  {"Content differs":<28}: {YELLOW}{len(result.content_differs):4d}{NC}')
    if result.type_differs:
        print(f'  {"Type/auxtype differs":<28}: {RED}{len(result.type_differs):4d}{NC}')
    if result.rsrc_changed:
        print(f'  {"Resource fork changed":<28}: {YELLOW}{len(result.rsrc_changed):4d}{NC}')
    if result.path_mismatch:
        print(f'  {"Path mismatches":<28}: {YELLOW}{len(result.path_mismatch):4d}{NC}  '
              f'{DIM}(correct name+content, wrong path){NC}')
    print(f'  {"Missing from source":<28}: {RED}{len(result.missing):4d}{NC}')
    print(f'  {"Extra in source":<28}: {CYAN}{len(result.extra):4d}{NC}')
    if result.exempt:
        print(f'  {"Exempt (GoldenGate SDK)":<28}: {DIM}{len(result.exempt):4d}{NC}')

    if opts.quiet:
        return

    # ── content differs ───────────────────────────────────────────────────────
    if show_dif and result.content_differs:
        section(f'CONTENT DIFFERS ({len(result.content_differs)})', YELLOW)
        print(f'  {"PATH":<{W}}  {"$TYPE":6}  {"REF":>9}  {"SRC":>9}  {"DELTA":>8}')
        show_omf = getattr(opts, 'omf', True) and not opts.quiet
        for ref_e, src_e in result.content_differs:
            delta = src_e.data_size - ref_e.data_size
            col   = GREEN if delta == 0 else (YELLOW if delta > 0 else DIM)
            print(f'  {ref_e.prodos_path:<{W}}  ${ref_e.type_hex:<5}  '
                  f'{_fmt_size(ref_e.data_size):>9}  {_fmt_size(src_e.data_size):>9}  '
                  f'{col}{_fmt_delta(delta):>8}{NC}')
            if verbose:
                print(f'  {"":{W+2}}  ref={ref_e.sha256[:24]}...')
                print(f'  {"":{W+2}}  src={src_e.sha256[:24]}...')
            if show_omf and ref_e.is_binary:
                omf_lines = _omf_diff_for_entry(ref_e, src_e, ref_info, src_info)
                if omf_lines:
                    for line in omf_lines:
                        print(line)

    # ── path mismatches ───────────────────────────────────────────────────────
    if show_dif and result.path_mismatch:
        section(f'PATH MISMATCHES ({len(result.path_mismatch)})  '
                f'— correct name+content, wrong location', YELLOW)
        for pm in result.path_mismatch:
            print(f'  {pm.ref_entry.prodos_path:<{W}}')
            print(f'  {"":4}→ found at  {pm.src_entry.prodos_path}')
            print(f'  {"":4}   ({pm.note})')

    # ── type differs ─────────────────────────────────────────────────────────
    if show_dif and result.type_differs:
        section(f'TYPE/AUXTYPE DIFFERS ({len(result.type_differs)})', RED)
        for ref_e, src_e in result.type_differs:
            print(f'  {ref_e.prodos_path}')
            print(f'    ref : ${ref_e.type_hex} aux${ref_e.auxtype_hex} ({ref_e.type_name}) '
                  f'{_fmt_size(ref_e.data_size)}')
            print(f'    src : ${src_e.type_hex} aux${src_e.auxtype_hex} ({src_e.type_name}) '
                  f'{_fmt_size(src_e.data_size)}')

    # ── resource fork changed ─────────────────────────────────────────────────
    if show_dif and result.rsrc_changed:
        section(f'RESOURCE FORK CHANGED ({len(result.rsrc_changed)})', YELLOW)
        for ref_e, src_e, note in result.rsrc_changed:
            tag = f'rsrc {note}'
            if note in ('added', 'removed'):
                ref_sz = f'{_fmt_size(ref_e.rsrc_size)}' if ref_e.has_resource_fork else '–'
                src_sz = f'{_fmt_size(src_e.rsrc_size)}' if src_e.has_resource_fork else '–'
                tag += f'  ref={ref_sz} src={src_sz}'
            print(f'  {ref_e.prodos_path:<{W}}  {tag}')

    # ── missing ───────────────────────────────────────────────────────────────
    if show_mis and result.missing:
        section(f'MISSING FROM SOURCE ({len(result.missing)})  — in reference, not built', RED)
        by_type: Dict[str, List[FileEntry]] = {}
        for e in result.missing:
            by_type.setdefault(e.type_name, []).append(e)
        for type_name in sorted(by_type):
            entries = by_type[type_name]
            sample  = entries[0]
            print(f'\n  {BOLD}{type_name}/${sample.type_hex}:{NC}')
            for e in entries:
                print(f'    {e.prodos_path:<{W-2}}  ref={_fmt_size(e.data_size):>8}')

    # ── extra ─────────────────────────────────────────────────────────────────
    if show_ext and result.extra:
        section(f'EXTRA IN SOURCE ({len(result.extra)})  — built but not in reference', CYAN)
        for e in result.extra:
            tag = f'{e.type_name}/${e.type_hex}'
            print(f'  {e.prodos_path:<{W}}  [{tag:<9}]  {_fmt_size(e.data_size):>8}')

    # ── identical ─────────────────────────────────────────────────────────────
    if show_ide and result.identical:
        section(f'IDENTICAL ({len(result.identical)})', GREEN)
        for ref_e, src_e in result.identical:
            tag = f'{ref_e.type_name}/${ref_e.type_hex}'
            print(f'  {ref_e.prodos_path:<{W}}  [{tag:<9}]  {_fmt_size(ref_e.data_size):>8}')
            if verbose:
                print(f'  {"":{W+2}}  sha256={ref_e.sha256[:32]}...')

    # ── exempt ────────────────────────────────────────────────────────────────
    if show_all and result.exempt:
        section(f'EXEMPT ({len(result.exempt)})  — provided by GoldenGate SDK', DIM)
        for e in result.exempt:
            print(f'  {DIM}{e.prodos_path:<{W}}  ref={_fmt_size(e.data_size):>8}  (GoldenGate){NC}')

    print()

# ── JSON output ───────────────────────────────────────────────────────────────

def emit_json(result: CompareResult, ref_info: SourceInfo, src_info: SourceInfo) -> None:
    def _fe(e: FileEntry) -> dict:
        return {'path': e.prodos_path, 'type': e.type_hex, 'auxtype': e.auxtype_hex,
                'size': e.data_size, 'sha256': e.sha256}

    out = {
        'cowdiff_version': VERSION,
        'generated': datetime.now(timezone.utc).isoformat(),
        'reference': str(ref_info.original_path),
        'source':    str(src_info.original_path),
        'summary': {
            'identical':        len(result.identical),
            'content_differs':  len(result.content_differs),
            'type_differs':     len(result.type_differs),
            'rsrc_changed':     len(result.rsrc_changed),
            'path_mismatch':    len(result.path_mismatch),
            'missing':          len(result.missing),
            'extra':            len(result.extra),
            'exempt':           len(result.exempt),
        },
        'identical': [
            {**_fe(r), 'src_path': s.prodos_path}
            for r, s in result.identical
        ],
        'content_differs': [
            {**_fe(r), 'src_size': s.data_size, 'delta': s.data_size - r.data_size,
             'src_sha256': s.sha256}
            for r, s in result.content_differs
        ],
        'type_differs': [
            {**_fe(r), 'src_type': s.type_hex, 'src_auxtype': s.auxtype_hex}
            for r, s in result.type_differs
        ],
        'rsrc_changed': [
            {**_fe(r), 'note': n}
            for r, s, n in result.rsrc_changed
        ],
        'path_mismatch': [
            {'ref_path': pm.ref_entry.prodos_path, 'src_path': pm.src_entry.prodos_path,
             'size': pm.ref_entry.data_size, 'sha256': pm.ref_entry.sha256}
            for pm in result.path_mismatch
        ],
        'missing': [_fe(e) for e in result.missing],
        'extra':   [_fe(e) for e in result.extra],
        'exempt':  [_fe(e) for e in result.exempt],
    }
    print(json.dumps(out, indent=2))

# ── cache subcommand ──────────────────────────────────────────────────────────

def cmd_cache(args: argparse.Namespace) -> None:
    root = Path(args.cache_dir).expanduser() if args.cache_dir else CACHE_ROOT

    if args.clear:
        if not root.exists():
            print('Cache is already empty.')
            return
        size = sum(f.stat().st_size for f in root.rglob('*') if f.is_file())
        shutil.rmtree(root)
        print(f'Cleared {_fmt_size(size)} from {root}')
        return

    # Default: --list
    if not root.exists():
        print('Cache is empty.')
        return
    entries = sorted(root.iterdir())
    if not entries:
        print('Cache is empty.')
        return
    total_size = 0
    print(f'Cache root: {root}\n')
    print(f'  {"SHA256 PREFIX":18}  {"SOURCE IMAGE":<38}  {"DATE":10}  {"FILES":>5}  {"SIZE":>8}')
    print(f'  {"─"*18}  {"─"*38}  {"─"*10}  {"─"*5}  {"─"*8}')
    for d in entries:
        if not d.is_dir():
            continue
        size = sum(f.stat().st_size for f in d.rglob('*') if f.is_file())
        total_size += size
        meta_path = d / 'metadata.json'
        label, date_str, n_files = '?', '?', 0
        if meta_path.exists():
            try:
                with open(meta_path) as f:
                    m = json.load(f)
                img = m.get('source_image') or ''
                label    = Path(img).name if img else '(directory scan)'
                date_str = (m.get('generated') or '')[:10]
                n_files  = m.get('stats', {}).get('files', 0)
            except Exception:
                pass
        print(f'  {d.name[:18]:<18}  {label:<38}  {date_str:10}  {n_files:5}  {_fmt_size(size):>8}')
    print(f'\n  Total: {_fmt_size(total_size)} in {len(entries)} cached extraction(s)')


# ── extract subcommand ────────────────────────────────────────────────────────

def cmd_extract(args: argparse.Namespace) -> None:
    cadius = find_cadius(args.cadius)
    image  = Path(args.image).expanduser().resolve()

    if not image.exists():
        print(f'ERROR: {image} not found', file=sys.stderr)
        sys.exit(1)
    if image.suffix.lower() not in DISK_EXTS:
        print(f'WARNING: {image.suffix!r} is not a recognised disk image suffix', file=sys.stderr)

    sha = hash_image(image, quiet=args.quiet)

    out_dir     = Path(args.out).expanduser().resolve() if args.out else None
    extract_to  = out_dir if out_dir else _cache_dir(sha)
    use_cache   = out_dir is None

    if use_cache and not args.no_cache and _cache_valid(extract_to, sha):
        if not args.quiet:
            with open(extract_to / 'metadata.json') as f:
                m = json.load(f)
            n = m['stats']['files']
            print(f'  Cache hit — {n} files, metadata current')
    else:
        if extract_to.exists():
            shutil.rmtree(extract_to)
        if not args.quiet:
            print(f'  Extracting {image.name} with cadius...', end=' ', flush=True)
        files, folders = run_cadius_extract(cadius, image, extract_to,
                                            verbose=getattr(args, 'verbose', False))
        if not args.quiet:
            print(f'{files} files, {folders} folders')
            print(f'  Generating metadata...', end=' ', flush=True)
        meta = generate_metadata(extract_to, image_path=image,
                                 image_sha256=sha,
                                 verbose=getattr(args, 'verbose', False))
        if not args.quiet:
            print(f'{meta["stats"]["files"]} entries → metadata.json')

    # Always print the extraction directory as the last line (scriptable)
    print(extract_to)


# ── compare subcommand ────────────────────────────────────────────────────────

def cmd_compare(args: argparse.Namespace) -> None:
    cadius     = find_cadius(args.cadius)
    cache_root = Path(args.cache_dir).expanduser() if args.cache_dir else CACHE_ROOT
    quiet      = getattr(args, 'quiet', False)

    if not quiet:
        print(f'Resolving reference: {args.reference}')
    ref_manifest, ref_info = resolve_input(
        args.reference, cadius, cache_root,
        no_cache=args.no_cache, quiet=quiet,
    )

    if not quiet:
        print(f'Resolving source   : {args.source}')
    src_manifest, src_info = resolve_input(
        args.source, cadius, cache_root,
        no_cache=args.no_cache, quiet=quiet,
    )

    # Optional filters
    if args.types:
        keep = {t.upper().lstrip('$') for t in args.types.split(',')}
        ref_manifest = {k: v for k, v in ref_manifest.items() if v.type_hex in keep}
        src_manifest = {k: v for k, v in src_manifest.items() if v.type_hex in keep}

    if args.no_text:
        skip = {'04', '06', '00', '0D'}
        ref_manifest = {k: v for k, v in ref_manifest.items() if v.type_hex.upper() not in skip}
        src_manifest = {k: v for k, v in src_manifest.items() if v.type_hex.upper() not in skip}

    result = compare_manifests(ref_manifest, src_manifest)

    if args.json:
        emit_json(result, ref_info, src_info)
    else:
        print_report(result, ref_info, src_info, args)

# ── argument parser ───────────────────────────────────────────────────────────

def _add_compare_args(p: argparse.ArgumentParser) -> None:
    p.add_argument('reference', help='Reference: disk image (.po/.2mg/.hdv), directory, or metadata.json')
    p.add_argument('source',    help='Source:    disk image (.po/.2mg/.hdv), directory, or metadata.json')
    p.add_argument('--cadius',     metavar='PATH', help='Path to cadius binary')
    p.add_argument('--cache-dir',  metavar='DIR',  help='Override cache root (default: ~/.cache/cowdiff/)')
    p.add_argument('--no-cache',   action='store_true', help='Force re-extraction even if cache is valid')
    p.add_argument('--types',      metavar='B5,B2', help='Comma-separated ProDOS hex type filter (e.g. B5,B2,BB)')
    p.add_argument('--no-text',    action='store_true', help='Exclude text/config files ($04,$06,$00,$0D)')
    p.add_argument('--missing',    action='store_true', help='Show only MISSING entries')
    p.add_argument('--extra',      action='store_true', help='Show only EXTRA entries')
    p.add_argument('--different',  action='store_true', help='Show only CONTENT_DIFFERS, PATH_MISMATCH, TYPE_DIFFERS')
    p.add_argument('--identical',  action='store_true', help='Show only IDENTICAL entries')
    p.add_argument('--json',       action='store_true', help='Emit machine-readable JSON')
    p.add_argument('--no-omf',  dest='omf', action='store_false',
                   help='Suppress OMF segment comparison for CONTENT DIFFERS entries (default: on)')
    p.add_argument('-v', '--verbose', action='store_true', help='Show SHA-256 for each file')
    p.add_argument('-q', '--quiet',   action='store_true', help='Summary stats only')
    p.set_defaults(omf=True)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog='cowdiff',
        description='GNO ProDOS disk image extraction and comparison tool',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
examples:
  cowdiff gno.po gno-built.2mg                    compare two disk images
  cowdiff compare gno.po gno-built.2mg            same, explicit subcommand
  cowdiff /expanded/ gno-built.2mg                compare pre-extracted dir to image
  cowdiff metadata.json gno-built.2mg             compare using existing metadata
  cowdiff gno.po gno-built.2mg --missing          show only what's missing
  cowdiff gno.po gno-built.2mg --types B5,BB      executables and drivers only
  cowdiff extract gno.po                          extract to cache; print path
  cowdiff extract gno.po --out /my/dir/           extract to specific directory
  cowdiff cache --list                            show cached extractions
  cowdiff cache --clear                           delete all cached data
""")
    parser.add_argument('--version', action='version', version=f'cowdiff {VERSION}')

    sub = parser.add_subparsers(dest='command')

    # extract
    p_ext = sub.add_parser('extract', help='Extract a disk image (to cache or --out directory)')
    p_ext.add_argument('image', help='Disk image file (.po, .2mg, .hdv)')
    p_ext.add_argument('--out',      metavar='DIR',  help='Extract to this directory (bypasses cache)')
    p_ext.add_argument('--cadius',   metavar='PATH', help='Path to cadius binary')
    p_ext.add_argument('--no-cache', action='store_true', help='Force re-extraction')
    p_ext.add_argument('-v', '--verbose', action='store_true')
    p_ext.add_argument('-q', '--quiet',   action='store_true')

    # cache
    p_cache = sub.add_parser('cache', help='Manage the extraction cache (~/.cache/cowdiff/)')
    cg = p_cache.add_mutually_exclusive_group()
    cg.add_argument('--list',  action='store_true', default=True,  help='List cached extractions (default)')
    cg.add_argument('--clear', action='store_true', default=False, help='Delete all cached extractions')
    p_cache.add_argument('--cache-dir', metavar='DIR', help='Override cache root')

    # compare (explicit)
    p_cmp = sub.add_parser('compare', help='Compare two disk images or extracted directories')
    _add_compare_args(p_cmp)

    return parser


def main() -> None:
    # Allow bare: cowdiff <ref> <src> [opts]  (no explicit 'compare' subcommand)
    # Detect: first arg is not a known subcommand and not a flag → inject 'compare'
    known_subcmds = {'extract', 'cache', 'compare', '--version', '--help', '-h'}
    if len(sys.argv) > 1 and sys.argv[1] not in known_subcmds:
        sys.argv.insert(1, 'compare')

    parser = build_parser()
    args   = parser.parse_args()

    if args.command is None:
        parser.print_help()
        sys.exit(0)

    try:
        if args.command == 'extract':
            cmd_extract(args)
        elif args.command == 'cache':
            cmd_cache(args)
        elif args.command == 'compare':
            cmd_compare(args)
    except (FileNotFoundError, ValueError, RuntimeError) as exc:
        print(f'{RED}ERROR:{NC} {exc}', file=sys.stderr)
        sys.exit(1)
    except KeyboardInterrupt:
        print('\nInterrupted.', file=sys.stderr)
        sys.exit(130)


if __name__ == '__main__':
    main()
