/**************************************************************
*
*  clinker.c -- ORCA/C reimplementation of the ORCA/M linker
*
*  Accepts the same command-line interface as the assembly
*  linker.  Produces identical OMF v2 output suitable for
*  loading by GS/OS.
*
*  Usage:
*    clinker [flags] file ... [keep=outfile]
*
*  Flags (same as asm linker):
*    +L    list segment info
*    +S    list symbol table after link
*    -X    disable express-load segment (default: enabled)
*    +M    memory-only link (no keep file written)
*    -C    disable compact records
*    -P    disable progress messages (default: show progress)
*
*  Shell variable:
*    gsplusSymbols=1   inject WDM prologue + write .symbols file
*
**************************************************************/

#pragma keep "clinker"
#pragma optimize 9

#include "clinker.h"

/* ----------------------------------------------------------
   Global state
   ---------------------------------------------------------- */

BOOLEAN  opt_list     = FALSE;
BOOLEAN  opt_symbols  = FALSE;
BOOLEAN  opt_express  = TRUE;  /* ExpressLoad on by default (matches iix link); -X disables */
BOOLEAN  opt_memory   = FALSE;
BOOLEAN  opt_compact  = TRUE;
BOOLEAN  opt_progress = TRUE;
BOOLEAN  opt_gsplus   = FALSE;
char    *keepName = NULL;   /* malloc'd in main() */
char    *baseName = NULL;

int      numErrors  = 0;
InputFile *inputFiles = NULL;
InputFile *inputTail  = NULL;
LibFile   *libFiles   = NULL;
OutSeg    *outSegs    = NULL;
int        numOutSegs = 0;
dword      sfSig      = 0;
int        lastDataNumber = 0;  /* link-wide data-area counter */

/* ----------------------------------------------------------
   Error reporting
   ---------------------------------------------------------- */

void LinkError(const char *msg, const char *name)
{
numErrors++;
if (name && name[0])
    fprintf(stderr, "clinker: error: %s: %s\n", msg, name);
else
    fprintf(stderr, "clinker: error: %s\n", msg);
}

void FatalError(const char *msg)
{
fprintf(stderr, "clinker: fatal: %s\n", msg);
exit(1);
}

/* ----------------------------------------------------------
   Output segment management
   ---------------------------------------------------------- */

OutSeg *FindOrCreateOutSeg(const char *loadName, const char *segName,
                            word kind)
{
OutSeg *s;

/* Merge key is LOADNAME only.  Per GS/OS Reference Appendix F
 * LOADNAME is "the name of the load segment that will contain the
 * code generated by the linker for this segment; more than one
 * segment in an object file can be merged by the linker into a
 * single segment in the load file."  The spec further states that
 * when merged segments have different KINDs, "the segment KIND of
 * the first object segment determines the segment KIND of the
 * entire load segment" — so we match on loadName alone, keep the
 * first-seen KIND, and do not require segType equality. */
for (s = outSegs; s; s = s->next) {
    if (strcmp(s->loadName, loadName) == 0) {
        /* Merge this segment's KIND flag bits into the output per the
         * stock ORCA/M linker rule (linker/out.asm:252-310, CheckHeader):
         *   bits $1D00 are ORed  — set if ANY contributing seg has them
         *   bits $E200 are ANDed — set only if ALL contributing segs do
         * The AND on $E200 is why PRIVATE ($4000) and DYNAMIC ($8000)
         * clear on output whenever any merged input lacked the bit.
         * Low byte (segType) stays as first-seen. */
        word orBits  = (word)(kind & 0x1D00);
        word andMask = (word)((kind & 0xE200) | 0x1DFF);
        s->kind = (word)((s->kind | orBits) & andMask);
        return s;
        }
    }

/* Create a new output segment */
s = (OutSeg *)malloc(sizeof(OutSeg));
if (!s) FatalError("out of memory (OutSeg)");
memset(s, 0, sizeof(OutSeg));

strncpy(s->loadName, loadName, NAME_MAX - 1);
strncpy(s->segName,  segName,  NAME_MAX - 1);
s->segType   = (word)(kind & 0x1F);
/* First contributor's KIND is taken verbatim, less the $0100 bankOrg
 * bit (stock CheckHeader at linker/out.asm:262 does `AND #$FEFF`).
 * Subsequent merges refine this per the OR/AND masks above. */
s->kind      = (word)(kind & ~0x0100);
s->banksize  = 0x10000L;
s->segNum    = ++numOutSegs;
s->length    = 0;

/* Append to list */
if (!outSegs) {
    outSegs = s;
    } else {
    OutSeg *t;
    for (t = outSegs; t->next; t = t->next) /* walk to end */ ;
    t->next = s;
    }

return s;
}

OutSeg *OutSegByNum(int n)
{
OutSeg *s;
for (s = outSegs; s; s = s->next)
    if (s->segNum == n) return s;
return NULL;
}

/* ----------------------------------------------------------
   Output data buffer helpers
   ---------------------------------------------------------- */

void GrowData(OutSeg *seg, long need)
{
long required = seg->dataLen + need + 16;
if (required <= seg->dataAlloc) return;
seg->data = (byte *)realloc(seg->data, (size_t)required);
if (!seg->data) FatalError("out of memory (GrowData)");
memset(seg->data + seg->dataAlloc, 0,
       (size_t)(required - seg->dataAlloc));
seg->dataAlloc = required;
}

void EmitData(OutSeg *seg, const byte *src, long len)
{
if (len <= 0) return;
GrowData(seg, len);
memcpy(seg->data + seg->dataLen, src, (size_t)len);
seg->dataLen += len;
}

void EmitZero(OutSeg *seg, long len)
{
if (len <= 0) return;
GrowData(seg, len);
memset(seg->data + seg->dataLen, 0, (size_t)len);
seg->dataLen += len;
}

/* ----------------------------------------------------------
   Relocation record management
   ---------------------------------------------------------- */

void AppendReloc(OutSeg *seg, long pc, byte patchLen, byte shift,
                 long value, int type, int segNum, int fileNum)
{
RelocRec *r = (RelocRec *)malloc(sizeof(RelocRec));
if (!r) FatalError("out of memory (RelocRec)");
r->pc       = pc;
r->patchLen = patchLen;
r->shift    = shift;
r->value    = value;
r->type     = type;
r->segNum   = segNum;
r->fileNum  = fileNum;
r->next     = NULL;

if (!seg->relocHead)
    seg->relocHead = r;
else
    seg->relocTail->next = r;
seg->relocTail = r;
}

/* GSplus signature init + .symbols sidecar writer live in gsplus.c.
 * Output file writing lives in out.c. */

/* ----------------------------------------------------------
   CLI parsing
   ---------------------------------------------------------- */

static void ParseFlag(const char *arg)
{
char sign = arg[0];  /* '+' or '-' */
char flag = (char)toupper((int)arg[1]);

if (sign == '+') {
    if      (flag == 'L') opt_list     = TRUE;
    else if (flag == 'S') opt_symbols  = TRUE;
    else if (flag == 'M') opt_memory   = TRUE;
    else if (flag == 'X') opt_express  = FALSE;  /* +X = no express (same as -X in asm) */
    else fprintf(stderr, "clinker: unknown flag: %s\n", arg);
    } else {
    if      (flag == 'X') opt_express  = FALSE;
    else if (flag == 'C') opt_compact  = FALSE;
    else if (flag == 'P') opt_progress = FALSE;
    else fprintf(stderr, "clinker: unknown flag: %s\n", arg);
    }
}

void SetBaseName(void)
{
/* Extract the last path component, strip extension */
char *slash, *dot;
int i;

strncpy(baseName, keepName, PATH_MAX - 1);
slash = strrchr(baseName, '/');
if (!slash) slash = strrchr(baseName, ':');  /* GS/OS path separator */
if (slash)
    memmove(baseName, slash + 1, strlen(slash));

dot = strrchr(baseName, '.');
if (dot) *dot = 0;

/* Uppercase */
for (i = 0; baseName[i]; i++)
    baseName[i] = (char)toupper((int)baseName[i]);
}

/* Open an input file (or stem with sibling-family ROOT/.a/.B search)
 * and append to the inputFiles list. Returns TRUE on success. */
int fileSeqCounter = 0;

BOOLEAN AddInputFile(const char *arg)
{
InputFile *tail;
int  noExt;
char tryName[PATH_MAX];
int  added = 0;
static const char *exts[] = { ".ROOT", ".root",
                              ".a",    ".A",
                              ".B",    ".b",
                              NULL };
static const int   groupEnd[] = { 2, 4, 6 };  /* first ext per group */

if (!arg || !arg[0]) return FALSE;

/* Find current tail */
tail = inputTail;

noExt = !strchr(arg, '.');

if (noExt) {
    int g, i;
    FILE *rawFp;

    /* Direct-file path: if arg names an existing file as-is (e.g. a
     * positional library like /Library/GoldenGate/Libraries/SysFloat,
     * or an extension-less object), peek OMF KIND at offset 20 and
     * route accordingly — $08 → library, else regular input. Skips
     * the sibling-family expansion entirely when the raw path hits. */
    rawFp = fopen(arg, "rb");
    if (rawFp) {
        int k0, k1, kind;
        fseek(rawFp, 20L, SEEK_SET);
        k0 = fgetc(rawFp);
        k1 = fgetc(rawFp);
        kind = (k0 != EOF && k1 != EOF) ? (k0 | (k1 << 8)) : 0;
        fseek(rawFp, 0L, SEEK_SET);

        if ((kind & 0x1F) == 0x08) {
            fclose(rawFp);
            return AddLibFile(arg);
            }
        {
        InputFile *inf = (InputFile *)malloc(sizeof(InputFile));
        if (!inf) FatalError("out of memory (InputFile)");
        memset(inf, 0, sizeof(InputFile));
        inf->fp      = rawFp;
        inf->fileNum = ++fileSeqCounter;
        strncpy(inf->name, arg, PATH_MAX - 1);
        if (!inputFiles) inputFiles = inf;
        else             tail->next = inf;
        inputTail = inf;
        return TRUE;
        }
        }

    /* Try each sibling family (ROOT → .a/.A → .B), adding
     * the first match in each family. */
    for (g = 0; g < (int)(sizeof groupEnd / sizeof groupEnd[0]); g++) {
        int start = (g == 0) ? 0 : groupEnd[g - 1];
        int stop  = groupEnd[g];
        FILE *fp = NULL;
        for (i = start; i < stop && !fp; i++) {
            snprintf(tryName, sizeof(tryName), "%s%s", arg, exts[i]);
            fp = fopen(tryName, "rb");
            }
        if (fp) {
            InputFile *inf = (InputFile *)malloc(sizeof(InputFile));
            if (!inf) FatalError("out of memory (InputFile)");
            memset(inf, 0, sizeof(InputFile));
            inf->fp      = fp;
            inf->fileNum = ++fileSeqCounter;
            strncpy(inf->name, tryName, PATH_MAX - 1);
            if (!inputFiles) inputFiles = inf;
            else             tail->next = inf;
            tail      = inf;
            inputTail = inf;
            added++;
            }
        }

    if (added == 0) {
        fprintf(stderr,
                "clinker: cannot open: %s(.ROOT|.a|.A|.B)\n", arg);
        numErrors++;
        return FALSE;
        }
    return TRUE;
    }
else {
    /* Explicit extension: open exactly what was specified. Fallback
     * for iix's compound-extension stripping — when iix hands us
     * `foo.root` because it stripped `.a` from `foo.root.a`, try
     * appending `.a`/`.A` before reporting failure. */
    InputFile *inf = (InputFile *)malloc(sizeof(InputFile));
    if (!inf) FatalError("out of memory (InputFile)");
    memset(inf, 0, sizeof(InputFile));
    inf->fp = fopen(arg, "rb");
    strncpy(inf->name, arg, PATH_MAX - 1);
    if (!inf->fp) {
        size_t alen = strlen(arg);
        int    alreadyDotA = (alen >= 2 && arg[alen-2] == '.' &&
                              (arg[alen-1] == 'a' || arg[alen-1] == 'A'));
        if (!alreadyDotA) {
            snprintf(tryName, sizeof(tryName), "%s.a", arg);
            inf->fp = fopen(tryName, "rb");
            if (!inf->fp) {
                snprintf(tryName, sizeof(tryName), "%s.A", arg);
                inf->fp = fopen(tryName, "rb");
                }
            if (inf->fp)
                strncpy(inf->name, tryName, PATH_MAX - 1);
            }
        }
    if (!inf->fp) {
        fprintf(stderr, "clinker: cannot open: %s\n", arg);
        free(inf);
        numErrors++;
        return FALSE;
        }
    inf->fileNum = ++fileSeqCounter;
    if (!inputFiles) inputFiles = inf;
    else             tail->next = inf;
    tail      = inf;
    inputTail = inf;
    return TRUE;
    }
}

/* Add a library file by path (lib=<path> semantics). Returns TRUE on
 * success. Silently skips (not error) if the file is not a valid lib
 * per `isLib == 0`; opens unconditionally otherwise. */
BOOLEAN AddLibFile(const char *path)
{
LibFile *lf;

if (!path || !path[0]) return FALSE;

lf = (LibFile *)malloc(sizeof(LibFile));
if (!lf) FatalError("out of memory (LibFile)");
memset(lf, 0, sizeof(LibFile));
strncpy(lf->path, path, PATH_MAX - 1);
lf->fp = fopen(lf->path, "rb");
if (!lf->fp) {
    fprintf(stderr, "clinker: cannot open library: %s\n", lf->path);
    free(lf);
    numErrors++;
    return FALSE;
    }
/* Append to match stock's file-list iteration order. Stock's NextFile
 * walks libraries in the order they're added to its file list (which
 * mirrors the prefix-13 directory enumeration or the command-line
 * `lib=` order). Prepending put clinker's libFiles in reverse, which
 * perturbed every library-symbol's merged offset vs stock. */
lf->next = NULL;
if (!libFiles) {
    libFiles = lf;
    } else {
    LibFile *t;
    for (t = libFiles; t->next; t = t->next) /* walk to tail */ ;
    t->next = lf;
    }
return TRUE;
}

static int GetParms(int argc, char *argv[])
{
int i;

for (i = 1; i <= argc; i++) {
    char *arg = argv[i];
    if (!arg || !arg[0]) continue;

    if (arg[0] == '-' && arg[1] == 'o' && arg[2] == 0) {
        /* -o <file>: same as keep=<file> */
        if (i + 1 <= argc && argv[i + 1]) {
            i++;
            strncpy(keepName, argv[i], PATH_MAX - 1);
            SetBaseName();
            }
        }
    else if (arg[0] == '+' || arg[0] == '-') {
        ParseFlag(arg);
        }
    else if ((toupper((int)arg[0]) == 'K') &&
             (toupper((int)arg[1]) == 'E') &&
             (toupper((int)arg[2]) == 'E') &&
             (toupper((int)arg[3]) == 'P') && arg[4] == '=') {
        strncpy(keepName, arg + 5, PATH_MAX - 1);
        SetBaseName();
        }
    else if ((toupper((int)arg[0]) == 'L') &&
             (toupper((int)arg[1]) == 'I') &&
             (toupper((int)arg[2]) == 'B') && arg[3] == '=') {
        AddLibFile(arg + 4);
        }
    else {
        AddInputFile(arg);
        }
    }
return (numErrors == 0);
}

/* ----------------------------------------------------------
   main
   ---------------------------------------------------------- */

int main(int argc, char *argv[])
{
int ok;
BOOLEAN fromShell;

/* Heap allocations. Policy: malloc for anything that doesn't have to be
 * static (see CONVENTIONS at top of file). */
SymInit();
keepName = (char *)malloc(PATH_MAX);
baseName = (char *)malloc(PATH_MAX);
if (!keepName || !baseName) FatalError("out of memory (name buffers)");
keepName[0] = '\0';
baseName[0] = '\0';

/* Try the iix-link path first: if the shell has LangInfo queued
 * (our symlink at /Library/GoldenGate/Languages/Linker → clinker
 * is being invoked as `iix link`), consume it. Otherwise fall
 * through to standard argv parsing for direct `iix clinker` use. */
fromShell = LoadFromLInfo();
if (!fromShell) {
    if (!GetParms(argc, argv)) {
        fprintf(stderr, "clinker: aborting due to errors\n");
        return 1;
        }
    }

if (!inputFiles) {
    fprintf(stderr, "clinker: no input files\n");
    if (fromShell) ReportToShell();
    return 1;
    }

/* Check shell variables */
InitGsplusSymbols();

if (opt_progress)
    puts("clinker 2.3.0 (ORCA/C)");

/* Pass 1: measure sizes and collect symbols */
ok = Pass1();
if (!ok && numErrors > 0) {
    fprintf(stderr, "clinker: %d error(s) in pass 1\n", numErrors);
    return 1;
    }

/* Library search: pull needed segments from library files */
if (libFiles)
    LibrarySearch();

/* Pass 2: generate output data */
ok = Pass2();
if (!ok && numErrors > 0) {
    fprintf(stderr, "clinker: %d error(s) in pass 2\n", numErrors);
    return 1;
    }

/* Write output file */
if (!opt_memory)
    ok = WriteOutput();

/* GSplus trace window + SourceGen platform-symbol sidecars */
if (opt_gsplus) {
    WriteSymbolFile();
    WriteSym65File();
    }

/* Optionally dump symbol table */
if (opt_symbols)
    SymDump();

/* List segments */
if (opt_list) {
    OutSeg *s;
    for (s = outSegs; s; s = s->next)
        printf("Segment %d: %-16s type=%04X length=%08lX\n",
               s->segNum, s->segName, (unsigned)s->segType, s->dataLen);
    }

if (numErrors) {
    fprintf(stderr, "clinker: %d error(s)\n", numErrors);
    return 1;
    }

return 0;
}
